import type { Address } from 'viem';
import catalog from './catalog.json';

export type StockToken = {
  symbol: string;
  name: string;
  address: Address;
  decimals: number;
  kind: 'stock' | 'etf';
  coingeckoId?: string;
  /** A $50 buy stayed within 3% of the reference price when the catalog was built */
  tradeable: boolean;
  /** Ondo-published logo URL, verified to serve an image when the catalog was built */
  logo?: string;
};

export type Asset = { address: Address; symbol: string; name: string; decimals: number; coingeckoId?: string; tradeable?: boolean; logo?: string };

/** Generated by scripts/build-catalog.mjs from Ondo's published token list, each token verified on-chain. */
const FEATURED = ['SPY', 'NVDA', 'TSLA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'QQQ', 'COIN', 'AMD', 'NFLX', 'PLTR', 'MSTR', 'HOOD', 'CRCL'];
const featuredRank = (t: StockToken) => {
  const i = FEATURED.indexOf(t.symbol.replace(/on$/, ''));
  return i === -1 ? FEATURED.length : i;
};

// Well-known names first, then A–Z.
export const TOKENS = (catalog.tokens as StockToken[])
  .slice()
  .sort((a, b) => featuredRank(a) - featuredRank(b) || a.symbol.localeCompare(b.symbol));
export const CATALOG_GENERATED_AT = catalog.generatedAt;

const byAddress = new Map(TOKENS.map((t) => [t.address.toLowerCase(), t]));
export const findToken = (address: string | null | undefined) => (address ? byAddress.get(address.toLowerCase()) : undefined);

// Verified on-chain on BNB Chain (symbol, 18 decimals).
export const USDT: Asset = { address: '0x55d398326f99059fF775485246999027B3197955', decimals: 18, symbol: 'USDT', name: 'Tether USD', coingeckoId: 'tether', logo: 'https://assets.coingecko.com/coins/images/325/small/Tether.png' };
export const USDC: Asset = { address: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', decimals: 18, symbol: 'USDC', name: 'USD Coin', coingeckoId: 'usd-coin', logo: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png' };
export const STABLES: Asset[] = [USDT, USDC];

/** BNB Chain's native gas token (not an ERC-20), shown on the dashboard alongside USDT. */
export const BNB = { symbol: 'BNB', name: 'BNB', decimals: 18, coingeckoId: 'binancecoin', logo: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png' };

/** Below this, a user may not be able to pay for an approval plus a swap. */
export const LOW_BNB_THRESHOLD = 0.0001;

export const TOKEN_DISCLOSURE =
  'Issued by Ondo Global Markets. Gives economic exposure to the underlying security; not the share itself and no shareholder voting rights. Not available to US persons. Ondo maintains an on-chain sanctions blocklist.';
