import type { Address } from 'viem';
import catalog from './catalog.json';

export type Issuer = 'ondo' | 'xstocks';

export type StockToken = {
  symbol: string;
  name: string;
  address: Address;
  decimals: number;
  issuer: Issuer;
  kind: 'stock' | 'etf';
  coingeckoId?: string;
  /** Had a live aggregator route for a $50 buy under 5% loss when the catalog was built */
  tradeable: boolean;
};

export type Asset = { address: Address; symbol: string; name: string; decimals: number; issuer?: Issuer; coingeckoId?: string; tradeable?: boolean };

/**
 * Generated by scripts/build-catalog.mjs from the issuers' own published lists
 * (Ondo's token CSV, xStocks' public assets API), each verified on-chain.
 */
export const TOKENS = catalog.tokens as StockToken[];
export const CATALOG_GENERATED_AT = catalog.generatedAt;

const byAddress = new Map(TOKENS.map((t) => [t.address.toLowerCase(), t]));
export const findToken = (address: string | null | undefined) => (address ? byAddress.get(address.toLowerCase()) : undefined);

// Verified on-chain on BNB Chain (symbol, 18 decimals).
export const USDT: Asset = { address: '0x55d398326f99059fF775485246999027B3197955', decimals: 18, symbol: 'USDT', name: 'Tether USD', coingeckoId: 'tether' };
export const USDC: Asset = { address: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', decimals: 18, symbol: 'USDC', name: 'USD Coin', coingeckoId: 'usd-coin' };
export const STABLES: Asset[] = [USDT, USDC];

export const ISSUER_LABEL: Record<Issuer, string> = { ondo: 'Ondo', xstocks: 'xStocks' };

export const ISSUER_DISCLOSURE: Record<Issuer, string> = {
  ondo: 'Issued by Ondo Global Markets. Gives economic exposure to the underlying security; not the share itself and no shareholder voting rights. Not available to US persons. Ondo maintains an on-chain sanctions blocklist.',
  xstocks: 'Issued by Backed (xStocks). Tracks the underlying share price, adjusted for dividends and splits; no shareholder voting rights. Not available to US persons.',
};
